export default {
  AUTH_CONTAINER: 'AUTH_CONTAINER',
  BOTTOM_CONTAINER: 'BOTTOM_CONTAINER',
  COMMON_CONTAINER: 'COMMON_CONTAINER',
  // bottom
  HOME_SCREEN: 'HOME_SCREEN',
  SERVICE_SCREEN: 'SERVICE_SCREEN',
  NOTIFY_SCREEN: 'NOTIFY_SCREEN',
  PROFILE_SCREEN: 'PROFILE_SCREEN',
};
